### ISSUE TITLE
Validation breaks when setting initial state.

### ISSUE THREAD

**Issue by mvandiest** [mbrookes/formsy-mui-demo#1]
Maybe there is some other way to do this, but I'm having the following problem...

Using `valueLink` breaks validation as it does not go through formsy's getValue() behavior. If you attempt to pass a `value` prop, as you normally would with formsy, then that prop is spread down to the material-ui component and bypasses formsy's getValue() behavior as well.

I'm in a crunch so I don't have time to make a PR, but I've proven, at least for FormsyText that the following example using destructuring works:

```
let FormsyText = React.createClass({
  mixins: [ Formsy.Mixin, FormComponentMixin ],
  render: function() {
    var { value, ...other } = this.props;
    return (
      <TextField
        value={this.getValue()}
        {...other}
        onChange={this.handleChange}
        errorText={this.getErrorMessage()} />
    );
  }
});
```

I don't know whether the same destructuring can be used for the other fields. But I thought I'd start a dialog here around this problem.

**Comment by mbrookes** [comment]
Thanks for the head-up. Please can you open this issue on the formsy-material-ui repo?

**Comment by mvandiest** [comment]
Sorry... I just realized I opened it in the wrong repo. I'll repost.

**Comment by mvandiest** [comment]
For posterity, the new issue is here:
https://github.com/mbrookes/formsy-material-ui/issues/3
