### ISSUE TITLE
Could I use with `Simple Schema, Collection2`?

### ISSUE THREAD

**Issue by thearabbit** [mbrookes/formsy-mui-demo#3]
Could I use with `Simple Schema, Collection2`?

**Comment by mbrookes** [comment]
I haven't used either of those, but if you can extract relevant fields, in theory you could use it to auto-populate some of the rules. Let me know how you get on! :+1:

**Comment by thearabbit** [comment]
Thanks for your reply.
I plan to use `Meteor 1.3, React JS` on `Mantra`.
Before I used `Collection2, SimpleSchema and AutoForm`..
After that I seen `Formsy` is popular for `React`.
So I would like to use it instead of `AutoForm` and integrate with `Collection2, SimpleSchema`.

**Comment by thearabbit** [comment]
`Formsy` don't have schema to check validate (owner), so it can't  integrate with `Simple Schema`.
Thank :+1:
