### ISSUE TITLE
Excuse me, I would like to use "admin layout of Material UI" with this example!

### ISSUE THREAD

**Issue by thearabbit** [mbrookes/formsy-mui-demo#8]
Excuse me, I would like to use "admin layout of Material UI" with this example.
could help me for any `admin layout` like `AdminLTE BS`?

**Comment by mbrookes** [comment]
https://gitter.im/callemall/material-ui

**Comment by thearabbit** [comment]
I need the `sample layout template` such as

![2016-02-29_20-07-39](https://cloud.githubusercontent.com/assets/4495160/13395244/27d08028-df20-11e5-836b-be800a8a18e9.png)

**Comment by mbrookes** [comment]
This is not a Material-UI forum. Thank you.

**Comment by thearabbit** [comment]
It mean that `sample template` such as

![2016-02-29_20-07-39](https://cloud.githubusercontent.com/assets/4495160/13414629/bcb7e030-df86-11e5-889f-8a02d7a6a89e.png)
